spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: 05377048490m
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082